services:
  frontend:
    build:
      dockerfile: ../docker/frontend/Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - IMAGE_DIR=screenshots/
    volumes:
      - ./data/screenshots:/app/public/screenshots
  server:
    build:
      dockerfile: ../docker/server/Dockerfile
      context: ./server
    ports:
      - "9000:9000"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./server/prod.yml:/app/prod.yml
      - screenshots-data:/app/screenshots
    depends_on:
      - db
    restart: always
  screenshot:
    build:
      dockerfile: ../docker/screenshot/Dockerfile
      context: ./screenshot
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    volumes:
      - ./data/screenshots:/app/screenshots
    restart: always
  db:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SCREENSHOT_SERVICE_URL=http://screenshot:8080/
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
volumes:
  pgdata:
