services:
  frontend:
    build:
      dockerfile: ../docker/frontend/Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NEXT_PUBLIC_IMAGE_DIR=/public/screenshots/
    volumes:
      - ./data/screenshots:/app/public/screenshots
  server:
    build:
      dockerfile: ../docker/server/Dockerfile
      context: ./server
    ports:
      - "9000:9000"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SCREENSHOT_SERVICE_URL=http://screenshot:8080/
      - FINDFIRST_SCREENSHOT_LOCATION=/app/screenshots
    volumes:
      - ./server/prod.yml:/app/prod.yml
      - ./data/screenshots:/app/screenshots
    depends_on:
      - db
    restart: always
  screenshot:
    build:
      dockerfile: ../docker/screenshot/Dockerfile
      context: ./screenshot
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - FINDFIRST_SCREENSHOT_LOCATION=/app/screenshots
    volumes:
      - ./data/screenshots:/app/screenshots
    restart: always
  db:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    ports:
      - "8108:8108"
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
    volumes:
      - ./data/typesense-data:/data
    command: "--data-dir /data --enable-cors"
volumes:
  pgdata:
