services:
  frontend:
    build:
      dockerfile: ../docker/frontend/Dockerfile
      image: ghcr.io/r-sandor/findfirst-frontend:latest
      context: ./frontend
      args:
        BUILDENV: dev
    ports:
      - "3000:3000"
    volumes:
      - screenshots-data:/app/public/screenshots
  server:
    build:
      dockerfile: ../docker/server/Dockerfile
      image: ghcr.io/r-sandor/findfirst-server:latest
      context: ./server
    ports:
      - "9000:9000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/findfirst
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_MAIL_HOST=mail
    volumes:
      - screenshots-data:/app/screenshots
  screenshot:
    build:
      dockerfile: ../docker/screenshot/Dockerfile
      image: ghcr.io/r-sandor/findfirst-screenshot:latest
      context: ./screenshot
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - screenshots-data:/app/screenshots
  db:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  mail:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  screenshots-data:
  pgdata:
