services: 
  frontend:
    build: 
      dockerfile: ../docker/frontend/Dockerfile
      context: ./frontend
    ports: 
     - "3000:3000"
  server:
    build: 
      dockerfile: ../docker/server/Dockerfile
      context: ./server
    ports: 
     - "9000:9000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/findfirst
      - SPRING_PROFILES_ACTIVE=staging
  screenshot:
    build: 
      dockerfile: ../docker/screenshot/Dockerfile
      context: ./screenshot
    ports: 
     - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=staging
  db: 
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SCREENSHOT_SERVICE_URL=http://screenshot:8080/
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  mail: 
    image: mailhog/mailhog:latest
    ports: 
      - 1025:1025
      - 8025:8025
volumes:
  screenshots-data:
  pgdata:
