services:
  frontend:
    build:
      dockerfile: ../docker/frontend/Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
  server:
    build:
      args:
        - BUILDENV=prod
      dockerfile: ../docker/server/Dockerfile
      context: ./server
    ports:
      - "9000:9000"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./server/prod.yml:/app/prod.yml
    depends_on:
      - db
    restart: always
  db:
    build:
      context: ./docker/postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
