# docker-compose to spin up postgress for the project. For the project docker-compose. 
# To build and run all images in the app stack refer to ../docker-compose.yaml.
version: '3'
services:
  db: 
    image: postgres:15.4
    environment:
        # Local development only.
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
