name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './Store'
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build
        run: |
          make
          docker push ghcr.io/r-sandor/findfirst-frontend:latest
          docker push ghcr.io/r-sandor/findfirst-server:latest
          docker push ghcr.io/r-sandor/findfirst-screenshot:latest
