name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Java 17
        run: | 
          make build_server
          docker push ghcr.io/r-sandor/findfirst-server:latest
      # - name: Build
      #   run: |
      #     make
      #     docker push ghcr.io/r-sandor/findfirst-frontend:latest
      #     docker push ghcr.io/r-sandor/findfirst-server:latest
      #     docker push ghcr.io/r-sandor/findfirst-screenshot:latest
